services:
    grafana:
        image: grafana/grafana-enterprise
        container_name: grafana
        restart: unless-stopped
        ports:
            - '3000:3000'
        volumes:
            - grafana-storage:/var/lib/grafana
        networks:
            - grafana_nw
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
volumes:
    grafana-storage: { }

